name: CI

on: ['push']

jobs:
  tests:
    name: 'Python ${{ matrix.python-version }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install package and run unit tests
        run: |
          pip install --upgrade pip
          pip install -e .
          pytest
